=== JammDesigner/jammdesigner.github.io/XML/recetas.dtd
<!ELEMENT recetas (receta)+>
<!ATTLIST recetas
  value CDATA #FIXED>

<!ELEMENT receta (imagen,nombre,valor,proteinas,hidratos,grasas)>
<!ATTLIST receta
  value CDATA #FIXED>

<!ELEMENT imagen (#PCDATA)>
<!ATTLIST imagen
  value CDATA #FIXED>

<!ELEMENT nombre (#PCDATA)>
<!ATTLIST nombre
  value CDATA #FIXED>

<!ELEMENT valor (#PCDATA)>
<!ATTLIST valor
  value CDATA #FIXED>

<!ELEMENT proteinas (#PCDATA)>
<!ATTLIST proteinas
  value CDATA #FIXED>

<!ELEMENT hidratos (#PCDATA)>
<!ATTLIST hidratos
  value CDATA #FIXED>

<!ELEMENT grasas (#PCDATA)>
<!ATTLIST grasas
  value CDATA #FIXED>

=== JammDesigner/jammdesigner.github.io/XML/recetas.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="recetas.xsl"?>

<!DOCTYPE recetas SYSTEM "dtd/recetas.dtd">

<recetas>

	<receta>
		<imagen>https://haycosasmuynuestras.com/wp-content/uploads/2017/10/Codorniz-GRANDE.jpg</imagen>
		<nombre>Codorniz escabechada</nombre>
		<valor>458 kcal</valor>
		<proteinas>40,1 g</proteinas>
		<hidratos>4,4 g</hidratos>
		<grasas>29,2 g</grasas>
	</receta>

	<receta>
		<imagen>https://haycosasmuynuestras.com/wp-content/uploads/2017/10/Huevos-rotos-GRANDE.jpg</imagen>
		<nombre>Huevos rotos con boletus y trufa</nombre>
		<valor>442 kcal</valor>
		<proteinas>17,9 g</proteinas>
		<hidratos>15,8 g</hidratos>
		<grasas>33,4 g</grasas>
	</receta>

	<receta>
		<imagen>https://haycosasmuynuestras.com/wp-content/uploads/2017/09/rollo-GRANDE.jpg</imagen>
		<nombre>Rollitos de lenguado</nombre>
		<valor>538 kcal</valor>
		<proteinas>54,1 g</proteinas>
		<hidratos>19,5 g</hidratos>
		<grasas>24,7 g</grasas>
	</receta>

	<receta>
		<imagen>https://haycosasmuynuestras.com/wp-content/uploads/2017/04/Raviolis-GRANDE.jpg</imagen>
		<nombre>Raviolis rellenos</nombre>
		<valor>508 kcal</valor>
		<proteinas>23,4 g</proteinas>
		<hidratos>37,2 g</hidratos>
		<grasas>28,1 g</grasas>
	</receta>

</recetas>
